parameters:
#    scuola247_core.example.class: Scuola247\Bundle\CoreBundle\Example

services:
#    scuola247_core.example:
#        class: %scuola247_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
